// default package
// Generated 3 mars 2025, 15:44:26 by Hibernate Tools 5.6.15.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Applicationmessage generated by hbm2java
 */
@Entity
@Table(name="applicationmessage"
    ,schema="public"
)
public class Applicationmessage  implements java.io.Serializable {


     private int id;
     private Application application;
     private Joboffer joboffer;
     private Date date;
     private String message;

    public Applicationmessage() {
    }

    public Applicationmessage(int id, Application application, Joboffer joboffer, Date date, String message) {
       this.id = id;
       this.application = application;
       this.joboffer = joboffer;
       this.date = date;
       this.message = message;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="application_id", nullable=false)
    public Application getApplication() {
        return this.application;
    }
    
    public void setApplication(Application application) {
        this.application = application;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="job_offer_id", nullable=false)
    public Joboffer getJoboffer() {
        return this.joboffer;
    }
    
    public void setJoboffer(Joboffer joboffer) {
        this.joboffer = joboffer;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=13)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="message", nullable=false)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}


