// default package
// Generated 3 mars 2025, 15:44:26 by Hibernate Tools 5.6.15.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Application generated by hbm2java
 */
@Entity
@Table(name="application"
    ,schema="public"
)
public class Application  implements java.io.Serializable {


     private int id;
     private Candidate candidate;
     private Qualificationlevel qualificationlevel;
     private String cv;
     private Date applicationdate;
     private Set<Sector> sectors = new HashSet<Sector>(0);
     private Set<Joboffermessage> joboffermessages = new HashSet<Joboffermessage>(0);
     private Set<Applicationmessage> applicationmessages = new HashSet<Applicationmessage>(0);

    public Application() {
    }

	
    public Application(int id, Candidate candidate, String cv, Date applicationdate) {
        this.id = id;
        this.candidate = candidate;
        this.cv = cv;
        this.applicationdate = applicationdate;
    }
    public Application(int id, Candidate candidate, Qualificationlevel qualificationlevel, String cv, Date applicationdate, Set<Sector> sectors, Set<Joboffermessage> joboffermessages, Set<Applicationmessage> applicationmessages) {
       this.id = id;
       this.candidate = candidate;
       this.qualificationlevel = qualificationlevel;
       this.cv = cv;
       this.applicationdate = applicationdate;
       this.sectors = sectors;
       this.joboffermessages = joboffermessages;
       this.applicationmessages = applicationmessages;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="candidate_id", nullable=false)
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="qualification_level_id")
    public Qualificationlevel getQualificationlevel() {
        return this.qualificationlevel;
    }
    
    public void setQualificationlevel(Qualificationlevel qualificationlevel) {
        this.qualificationlevel = qualificationlevel;
    }

    
    @Column(name="cv", nullable=false)
    public String getCv() {
        return this.cv;
    }
    
    public void setCv(String cv) {
        this.cv = cv;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="applicationdate", nullable=false, length=13)
    public Date getApplicationdate() {
        return this.applicationdate;
    }
    
    public void setApplicationdate(Date applicationdate) {
        this.applicationdate = applicationdate;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="applicationsector", schema="public", joinColumns = { 
        @JoinColumn(name="application_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="sector_id", nullable=false, updatable=false) })
    public Set<Sector> getSectors() {
        return this.sectors;
    }
    
    public void setSectors(Set<Sector> sectors) {
        this.sectors = sectors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="application")
    public Set<Joboffermessage> getJoboffermessages() {
        return this.joboffermessages;
    }
    
    public void setJoboffermessages(Set<Joboffermessage> joboffermessages) {
        this.joboffermessages = joboffermessages;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="application")
    public Set<Applicationmessage> getApplicationmessages() {
        return this.applicationmessages;
    }
    
    public void setApplicationmessages(Set<Applicationmessage> applicationmessages) {
        this.applicationmessages = applicationmessages;
    }




}


