// default package
// Generated 3 mars 2025, 15:44:26 by Hibernate Tools 5.6.15.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Candidate generated by hbm2java
 */
@Entity
@Table(name="candidate"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="user_id") 
)
public class Candidate  implements java.io.Serializable {


     private int id;
     private Appuser appuser;
     private String lastname;
     private String firstname;
     private String city;
     private Set<Application> applications = new HashSet<Application>(0);

    public Candidate() {
    }

	
    public Candidate(int id, String lastname, String firstname) {
        this.id = id;
        this.lastname = lastname;
        this.firstname = firstname;
    }
    public Candidate(int id, Appuser appuser, String lastname, String firstname, String city, Set<Application> applications) {
       this.id = id;
       this.appuser = appuser;
       this.lastname = lastname;
       this.firstname = firstname;
       this.city = city;
       this.applications = applications;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", unique=true)
    public Appuser getAppuser() {
        return this.appuser;
    }
    
    public void setAppuser(Appuser appuser) {
        this.appuser = appuser;
    }

    
    @Column(name="lastname", nullable=false)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="firstname", nullable=false)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="city")
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidate")
    public Set<Application> getApplications() {
        return this.applications;
    }
    
    public void setApplications(Set<Application> applications) {
        this.applications = applications;
    }




}


