// default package
// Generated 3 mars 2025, 15:44:26 by Hibernate Tools 5.6.15.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Qualificationlevel generated by hbm2java
 */
@Entity
@Table(name="qualificationlevel"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="label") 
)
public class Qualificationlevel  implements java.io.Serializable {


     private int id;
     private String label;
     private Set<Joboffer> joboffers = new HashSet<Joboffer>(0);
     private Set<Application> applications = new HashSet<Application>(0);

    public Qualificationlevel() {
    }

	
    public Qualificationlevel(int id, String label) {
        this.id = id;
        this.label = label;
    }
    public Qualificationlevel(int id, String label, Set<Joboffer> joboffers, Set<Application> applications) {
       this.id = id;
       this.label = label;
       this.joboffers = joboffers;
       this.applications = applications;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="label", unique=true, nullable=false, length=50)
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="qualificationlevel")
    public Set<Joboffer> getJoboffers() {
        return this.joboffers;
    }
    
    public void setJoboffers(Set<Joboffer> joboffers) {
        this.joboffers = joboffers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="qualificationlevel")
    public Set<Application> getApplications() {
        return this.applications;
    }
    
    public void setApplications(Set<Application> applications) {
        this.applications = applications;
    }




}


