package fr.atlantique.imt.inf211.jobmngt.entity;
// Generated 3 mars 2025, 15:44:26 by Hibernate Tools 5.6.15.Final


import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import jakarta.persistence.*;

import java.util.HashSet;
import java.util.Set;

/**
 * Appuser generated by hbm2java
 */
@Entity
@Table(name = "appuser", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "mail"))
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class AppUser implements java.io.Serializable {


    private int id;
    private String mail;
    private String password;
    private String usertype;
    private String city;
    private Candidate candidate;
    private Company company;

    public AppUser() {
    }


    public AppUser(int id, String mail, String password) {
        this.id = id;
        this.mail = mail;
        this.password = password;
    }

    public AppUser(int id, String mail, String password, String usertype, String city, Candidate candidate, Company company) {
        this.id = id;
        this.mail = mail;
        this.password = password;
        this.usertype = usertype;
        this.city = city;
        this.candidate = candidate;
        this.company = company;
    }

    @Id
    @SequenceGenerator(name = "APPUSER_ID_GENERATOR", sequenceName = "APPUSER_ID_SEQ", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "APPUSER_ID_GENERATOR")


    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }


    @Column(name = "mail", unique = true, nullable = false, length = 50)
    public String getMail() {
        return this.mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }


    @Column(name = "password", nullable = false, length = 50)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }


    @Column(name = "usertype", length = 50)
    public String getUsertype() {
        return this.usertype;
    }

    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    @Column(name = "city")
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "appuser", cascade = CascadeType.ALL, orphanRemoval = true)
    public Candidate getCandidate() {
        return this.candidate;
    }

    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "appuser", cascade = CascadeType.ALL, orphanRemoval = true)
    public Company getCompany() {
        return this.company;
    }

    public void setCompany (Company company) {
        this.company = company;
    }


}


