package fr.atlantique.imt.inf211.jobmngt.entity;
// Generated Jan 29, 2025, 4:45:01 PM by Hibernate Tools 5.6.15.Final

import jakarta.persistence.GenerationType;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * Userapp generated by hbm2java
 */
@Entity
@Table(name = "appuser", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "mail"))
public class AppUser implements java.io.Serializable {

    private int id;
    private String mail;
    private String password;
    private String usertype;

    public AppUser() {
    }

    public AppUser(int id, String mail, String password, String usertype) {
        this.id = id;
        this.mail = mail;
        this.password = password;
        this.usertype = usertype;
    }

    @Id
    @SequenceGenerator(name = "APPUSER_ID_GENERATOR", sequenceName = "APPUSER_ID_SEQ", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "APPUSER_ID_GENERATOR")

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "mail", unique = true, nullable = false, length = 50)
    public String getMail() {
        return this.mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    @Column(name = "password", nullable = false, length = 50)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "usertype", length = 50)
    public String getUsertype() {
        return this.usertype;
    }

    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    @Override
    public String toString() {
        return "AppUser [id=" + id + ", mail=" + mail + ", usertype=" + usertype + "]";
    }

}
