package fr.atlantique.imt.inf211.jobmngt.entity;
// Generated 3 mars 2025, 15:44:26 by Hibernate Tools 5.6.15.Final


import jakarta.persistence.GenerationType;
import jakarta.persistence.SequenceGenerator;
 import jakarta.persistence.GeneratedValue;
 import com.fasterxml.jackson.annotation.JsonIdentityInfo;
 import com.fasterxml.jackson.annotation.ObjectIdGenerators;import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * Candidate generated by hbm2java
 */
@Entity
@Table(name="candidate"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="user_id") 
)
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class,property = "id")
public class Candidate  implements java.io.Serializable {


     private int id;
     private AppUser appuser;
     private String lastname;
     private String firstname;
     private Set<Application> applications = new HashSet<Application>(0);

    public Candidate() {
    }

	
    public Candidate(int id, String lastname, String firstname) {
        this.id = id;
        this.lastname = lastname;
        this.firstname = firstname;
    }
    public Candidate(int id, AppUser appuser, String lastname, String firstname, Set<Application> applications) {
       this.id = id;
       this.appuser = appuser;
       this.lastname = lastname;
       this.firstname = firstname;
       this.applications = applications;
    }
   
     @Id
	@SequenceGenerator(name = "CANDIDATE_ID_GENERATOR", sequenceName = "CANDIDATE_ID_SEQ",allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "CANDIDATE_ID_GENERATOR") 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", unique=true)
    public AppUser getAppuser() {
        return this.appuser;
    }
    
    public void setAppuser(AppUser appuser) {
        this.appuser = appuser;
    }

    
    @Column(name="lastname", nullable=false)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="firstname", nullable=false)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidate")
    public Set<Application> getApplications() {
        return this.applications;
    }
    
    public void setApplications(Set<Application> applications) {
        this.applications = applications;
    }




}


